# Generated by Django 3.2.8 on 2022-04-23 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0003_collage_school'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collage',
            old_name='school_id',
            new_name='school',
        ),
    ]
