# Generated by Django 3.2.8 on 2022-04-23 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0004_rename_school_id_collage_school'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('collage', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='demo.collage')),
            ],
        ),
    ]
