# Generated by Django 3.2.8 on 2022-04-23 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0005_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='adjoin',
            field=models.ManyToManyField(related_name='_demo_location_adjoin_+', to='demo.Location'),
        ),
    ]
