# Generated by Django 3.2.8 on 2022-04-23 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0006_location_adjoin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('collage', models.ManyToManyField(to='demo.Collage')),
            ],
        ),
    ]
